# Generated by Django 5.1 on 2024-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_document_aitext_extractedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='error',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aitext',
            name='classification',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='aitext',
            name='entity',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='aitext',
            name='sentiment',
            field=models.JSONField(),
        ),
    ]
