# Generated by Django 5.1 on 2024-08-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_document_error_alter_aitext_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
